<<<<<<< HEAD
[env]
PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
=======
# fly.toml app configuration file generated for nest-car-rental on 2025-06-18T07:20:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nest-car-rental'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
>>>>>>> 6a23ac56f873308bfd7911d8aa1c9d78dcfbc28f
